library(tidyverse)
library(ggplot2)
library(opendatatoronto)
library(dplyr)
package <- show_package("police-annual-statistical-report-arrested-and-charged-persons")
resources <- list_package_resources("police-annual-statistical-report-arrested-and-charged-persons")
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
data <- filter(datastore_resources, row_number()==1) %>% get_resource()
arrested_data <- filter(datastore_resources, row_number()==1) %>% get_resource()
